### ISSUE TITLE
终于有勇士对反人类的表格式开题报告下手了

### ISSUE THREAD

**Issue by charryzzz** [TomHeaven/nudtproposal#6]
手动点赞！
Ps：参考文献编译器为什么不能用bibtex？

**Comment by charryzzz** [comment]
还有一个问题，一级标题 section 的第二第三等标题前有空行，不知道应该怎么修改。还有第二页的说明和学校下发的模板也有交大差别。

**Comment by charryzzz** [comment]
section 之前空行是因为页眉设置问题，已经解决了，但是又发现了一个新问题😂开题报告方框和文本之间距离太近，比如某一章超过2页，它从第二页开始的第一行和表格之间的距离非常小。

**Comment by TomHeaven** [comment]
因为参考文献要放在表里，目前只有biber手撸了实现，bibtex不知道怎么实现。
因本人已经不用开题了，如果发现问题欢迎pull。
