### ISSUE TITLE
mac 下字体出现问题了

### ISSUE THREAD

**Issue by sunyongke** [TomHeaven/nudtproposal#8]
line 103: \CJKunderlinecolor undefined. \renewcommand{\CJKunderlinecolor}
line 290: File `zhspacing.sty' not found. \zihao
: You have requested document class `Style/nudtproposal', but the document class provides `nudtproposal'.

**Comment by TomHeaven** [comment]
这不字体问题，是你的tex编译环境缺包。建议按readme的教程安装编译环境。

**Comment by sunyongke** [comment]
非常感谢
